apvma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from rest_framework import routers

from apvma.core.views import home
from apvma.accounts import views as account_views
from apvma.reservations.views import ReservationViewSet

router = routers.DefaultRouter()
router.register(r'reservations', ReservationViewSet)

urlpatterns = [
    path('home/', home, name='home'),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='home', permanent=False), name='index'),

    # login urls
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('request_signup/', account_views.request_signup, name='request_signup'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),

    # password reset urls
    path('reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt',
        ),
        name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    # password change urls
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
         name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),

    # accountability urls
    path('accountability/', include('apvma.accountability.urls')),

    # reservations urls
    path('reservations/', include('apvma.reservations.urls')),

    # reservation calendar api
    path('api/', include(router.urls)),
    path('auth/', include('rest_framework.urls')),

    # contact_us urls
    path('contact_us', include('apvma.contact_us.urls')),

    # assembly urls
    path('assembly', include('apvma.assembly.urls')),

    # visitors urls
    path('visitors', include('apvma.visitors.urls')),
]

apvma/visitors/urls.py
from django.urls import path

from apvma.visitors.views import visitors

urlpatterns = [
    path('', visitors, name='visitors'),
    ]

apvma/visitors/models.py
from datetime import datetime

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from apvma.core.models import Apartment


class Visitor(models.Model):
    datetime = models.DateTimeField('estimada de chegada')
    description = models.TextField('nome / descrição', max_length=50)
    arrival_date = models.DateField('data_chegada', blank=True, null=True)
    arrival_time = models.TimeField('hora chegada', blank=True, null=True)
    exit_date = models.DateField('saída', blank=True, null=True)
    exit_time = models.TimeField('saída', blank=True, null=True)
    card = models.PositiveIntegerField('cartão', blank=True, null=True, validators=[MinValueValidator(1),
                                                                                    MaxValueValidator(60)])
    apartment = models.ForeignKey(Apartment,verbose_name='apartamento', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Visita Autorizada'
        verbose_name_plural = 'Visitas Autorizadas'
        ordering = ('-datetime', 'apartment', 'description')

    def save(self, *args, **kwargs):
        '''Auto save for arrival_date and exit_date when changing arrival_time and exit_time'''
        if self.arrival_time and not self.arrival_date:
            self.arrival_date = datetime.today()
        if self.exit_time and not self.exit_date:
            self.exit_date = datetime.today()

        return super(Visitor, self).save(*args, **kwargs)

    def clean_fields(self, exclude=None):
        """It must have a card when it has an arrival_date.
           Minimum card number: 1, Maximum card number: 60"""
        if self.arrival_time and not self.card:
            raise ValidationError('Selecione o cartão alocado para o visitante.')
        if self.arrival_time and self.card not in range(1, 61):
            raise ValidationError('Número de cartão inexistente. Cartões existentes: 1 a 60.')

apvma/visitors/forms.py
from django import forms
from apvma.visitors.models import Visitor


class AuthorizeVisitorForm(forms.ModelForm):
    class Meta:
        model = Visitor
        fields = ['datetime', 'description']

apvma/visitors/views.py
from datetime import datetime

from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test

from apvma.core.models import Apartment
from apvma.core.user_passes_tests import in_resident_group
from apvma.visitors.forms import AuthorizeVisitorForm
from apvma.visitors.models import Visitor


@login_required
@user_passes_test(in_resident_group, login_url='/home/')
def visitors(request):
    if request.method == 'POST':
        if 'new_authorization_button' in request.POST:
            new_authorization(request)

        if 'cancel_authorization_button' in request.POST:
            cancel_authorization(request)

        return HttpResponseRedirect(request.path)

    else:
        form = AuthorizeVisitorForm()
        my_visitors_planned = Visitor.objects.filter(
            apartment__user=request.user).filter(Q(exit_time=None) |
                                         Q(datetime__gte=datetime.today())).order_by('datetime')
        context = {'my_visitors_planned': my_visitors_planned,
                   'form': form}
        return render(request, 'visitors/visitors.html', context)

def new_authorization(request):
    _datetime = datetime.strptime(request.POST['datetime'], '%d/%m/%y - %H:%M')
    description = request.POST['description']
    apartment = Apartment.objects.get(user=request.user)
    Visitor.objects.create(datetime=_datetime,
                           description=description,
                           apartment=apartment)

    messages.success(request, 'Autorização enviada com sucesso.')


def cancel_authorization(request):
    """Delete a visitor object selected by user"""
    visit = Visitor.objects.get(pk=request.POST['cancel_authorization'])
    visit.delete()

    messages.success(request, 'Autorização cancelada com sucesso.')

apvma/visitors/templates/visitors/visitors.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}


    <!-- DateTimePicker script -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />


    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

    <!-- Visitor CSS style -->
    <link rel="stylesheet" href="{% static 'css/visitors.css' %}">
    <link rel="stylesheet" href="{% static 'css/visitors-mobile.css' %}">


{% endblock stylesheet %}


{% block content %}

    <div id="my_visits">
    <h3>Entradas autorizadas por mim:</h3>

        {% if my_visitors_planned %}

            <table width="85%" border="1" align="center" id="table_visits">
                <tr align="center" height="40" bgcolor="#E3E3E3">
                    <td width="25%"><b>ESTIMADA</b></td>
                    <td width="45%"><b>NOME / DESCRIÇÃO</b></td>
                    <td width="15%"><b>CHEGADA</b></td>
                    <td width="15%"><b>SAÍDA</b></td>
                </tr>
                {% for visit in my_visitors_planned %}
                    <tr align="center" height="30" id="visit_{{ visit.pk }}">
                        <td>{{ visit.datetime | date:'d/m/Y' }} - {{ visit.datetime | time:'H:i \h' }}</td>
                        <td align="left" style="padding-left: 5px">{{ visit.description }}</td>
                        <td>{{ visit.arrival_time | time:'H:i \h' }}</td>
                        <td>{{ visit.exit_time | time:'H:i \h' }}</td>
                    </tr>
                {% endfor %}
            </table>

            <form action="#" method="post">
                {% csrf_token %}

                  <input type="hidden" name="user" id="user" value="{{ request.user.pk }}">

                  <div class="form-group">
                    <label for="cancel_visitor_authorization" id="cancel_visitor_authorization">Cancelar autorização de entrada</label> <br/>
                    <select class="form-control" id="cancel_authorization" name="cancel_authorization" required>
                        <option disabled selected value>-----</option>
                        {% for visit in my_visitors_planned %}
                            <option value="{{ visit.pk }}">{{ visit.datetime | date:'d/m/y H:m'}}h - {{ visit.description }}</option>
                        {% endfor %}
                    </select>
                    <div align="center">
                        <button type="submit" class="btn btn-primary" name="cancel_authorization_button" id="cancel_authorization_button">Cancelar autorização</button>
                    </div>
                  </div>
            </form>
        {% else %}

            <p>Você não possui entradas autorizadas.</p>

        {% endif %}

    </div>

    <div id="authorize_visit">
        {% if request.user.is_authenticated %}
        <h3>Autorizar entrada:</h3>

            <form action="#" method="post" id="authorize_visitor">
            {% csrf_token %}
                <input type="hidden" name="user" id="user" value="{{ request.user }}">

                <div class="container">
                    <div class="form-group">
                      <div class="row">
                          <div class="col-md-12">
                              <div class="row">
                                  {{ form.datetime.label_tag }}
                                  {{ form.datetime }}
                              </div>
                              <div class="row" id="description_row">
                                  {{ form.description.label_tag }}
                                  {{ form.description }}
                              </div>
                          </div>
                          <div align="center" id="button_new_authorization">
                            <button type="submit" class="btn btn-primary" name="new_authorization_button" id="new_authorization_button">Enviar para a Portaria</button>
                          </div>
                      </div>
                  </div>
               </div>
                <row>

                </row>


            </form>

        {% endif %}
    </div>

    <script type="text/javascript">
        $('#id_datetime').datetimepicker({
            format: 'DD/MM/YY - HH:mm',
            sideBySide: true,
            locale: 'pt-br'
        });
    </script>
{% endblock content %}