apvma/reservations/urls.py
from django.urls import re_path

from apvma.reservations.views import reservation_calendar

urlpatterns = [
    re_path(r'^(?P<year>[\d]+)/(?P<month>[\d]+)/$', reservation_calendar, name='reservation_calendar'),
    ]

apvma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from rest_framework import routers

from apvma.core.views import home
from apvma.accounts import views as account_views
from apvma.reservations.views import ReservationViewSet

router = routers.DefaultRouter()
router.register(r'reservations', ReservationViewSet)

urlpatterns = [
    path('home/', home, name='home'),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='home', permanent=False), name='index'),

    # login urls
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('request_signup/', account_views.request_signup, name='request_signup'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),

    # password reset urls
    path('reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt',
        ),
        name='password_reset'),
    path('reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    # password change urls
    path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
         name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
         name='password_change_done'),

    # accountability urls
    path('accountability/', include('apvma.accountability.urls')),

    # reservations urls
    path('reservations/', include('apvma.reservations.urls')),

    # reservation calendar api
    path('api/', include(router.urls)),
    path('auth/', include('rest_framework.urls')),

    # contact_us urls
    path('contact_us', include('apvma.contact_us.urls')),

    # assembly urls
    path('assembly', include('apvma.assembly.urls')),

    # visitors urls
    path('visitors', include('apvma.visitors.urls')),
]

apvma/reservations/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils import timezone

from apvma.reservations.manager import ValidReservationManager


class Reservation(models.Model):
    SPOTS = (
        ('TP', 'Tapiri'),
        ('SF', 'Salão de Festas'),
        ('TA', 'Tapiri das Árvores'),
    )

    user = models.ForeignKey(User,verbose_name='apartamento', on_delete=models.CASCADE)
    date = models.DateField('data solicitada')
    spot = models.CharField('ambiente', max_length=2, choices=SPOTS)
    created_on = models.DateTimeField('data da solicitação', auto_now_add=True)
    paid = models.BooleanField('pago', default=False)
    canceled = models.BooleanField('cancelado', default=False)
    canceled_on = models.DateTimeField('cancelado em', blank=True, null=True)
    expires_on = models.DateTimeField('expira em', editable=False)

    def save(self, *args, **kwargs):
        '''Defines expires_on datetime when creating a reservation'''
        if not self.pk:
            days_valid = 1
            self.expires_on = timezone.now() + timedelta(days=days_valid)
        if self.canceled:
            self.canceled_on = timezone.now()

        return super(Reservation, self).save(*args, **kwargs)


    class Meta:
        verbose_name = 'reserva'
        verbose_name_plural = 'reservas'
        ordering = ('date',)

    def __str__(self):
        return '{} - {} - {}'.format(self.user.username, self.date, self.spot)

    def pay(self):
        """Changes the value of paid when the user pays the reservation. This will be
        set by the admin"""
        self.paid = True
        self.save()

    def cancel(self):
        """Changes the value of canceled to True when the user cancels the reservation"""
        self.canceled = True
        self.canceled_on = timezone.now()
        self.save()

    def get_color(self):
        """Defines the background color of each reservation line in the table"""
        if self.canceled or self.expired():
            return '#FF9A84' #red
        if self.paid:
            return '#9FFF99'  # green
        else:
            return 'white'

    def expired(self):
        """Returns True if reservation expires and no payment is done"""
        if self.paid:
            return False
        else:
            return self.expires_on < timezone.now()

    objects = models.Manager() # the default manager
    valid_reservations = ValidReservationManager() # valid reservation manager

    @property
    def status(self):
        """Defines the status of the reservation:
        when a reservation is created, it returns 'aguardando pagamento'
        when a reservation is canceled, it returns 'cancelada em '+ data de cancelamento'
        when a reservation is expired, it returns 'expirada por falta de pagamento'
        when a reservation is paid, it returns 'reserva confirmada'"""
        if self.canceled:
            return 'cancelada em {}'.format(self.canceled_on.date().strftime('%d/%m/%Y'))
        elif self.paid:
            return 'confirmada'
        elif self.expired():
            return 'expirada por falta de pagamento'
        else:
            return 'aguardando pagamento'


class TermsOfUse(models.Model):
    file = models.FileField(upload_to='reservations/termsofuse/',
                            validators=[FileExtensionValidator(['pdf'], 'O sistema só permite o upload de arquivos PDF.')])
    uploaded_on = models.DateTimeField('criado em', auto_now_add=True)

    class Meta:
        verbose_name = 'Regras de Uso de Ambiente'
        verbose_name_plural = verbose_name

    def save(self, *args, **kwargs):
        """It must exist only one file of Terms of Use"""
        if TermsOfUse.objects.exists() and not self.pk:
            raise ValidationError('Só pode existir 1 arquivo de Termos de Uso de Ambiente.')
        self.uploaded_on = timezone.now()
        return super(TermsOfUse, self).save(*args, **kwargs)

apvma/reservations/forms.py
from django import forms

from apvma.reservations.models import Reservation


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['user', 'date', 'spot']

apvma/reservations/views.py
from calendar import Calendar
from datetime import datetime, timedelta, date

from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from rest_framework.viewsets import ModelViewSet

from apvma.core.user_passes_tests import in_resident_group
from apvma.reservations.forms import ReservationForm
from apvma.reservations.models import Reservation, TermsOfUse
from apvma.reservations.serializer import ReservationSerializer


class ReservationViewSet(ModelViewSet):
    queryset = Reservation.objects.all()
    serializer_class = ReservationSerializer


def request_reservation(request):
    form = ReservationForm(request.POST)
    if not form.is_valid():
        return HttpResponseRedirect(request.path)

    user = request.user
    date = form.cleaned_data['date']
    spot = form.cleaned_data['spot']

    check_reservation = Reservation.valid_reservations.filter(
        date=date, spot=spot
    )

    month = date.month
    second_reservation_same_month = Reservation.valid_reservations.filter(user=user, date__month=month, spot=spot)

    if check_reservation:
        messages.warning(request, 'Já existe uma reserva para o local e data selecionados.')
    elif second_reservation_same_month:
        messages.warning(request, 'As regras de uso só permitem 1 reserva de cada ambiente por mês por permissionário.')
    else:
        reservation = form.save()
        messages.info(request,
                      'Reserva agendada com sucesso. Caso o pagamento não seja realizado em até 24 horas, a reserva será expirada.')


def cancel_reservation(request):
    reservation = Reservation.objects.get(pk=request.POST['cancel_reservation'])
    reservation.cancel()

    messages.success(request, 'Reserva cancelada com sucesso.')


@login_required
@user_passes_test(in_resident_group, login_url='/home/')
def reservation_calendar(request, year, month):
    if request.method == 'POST':
        if 'request_reservation_button' in request.POST:
            request_reservation(request)

        if 'cancel_reservation_button' in request.POST:
            cancel_reservation(request)

        return HttpResponseRedirect(request.path)

    else:

        try:
            selected_date = date(int(year), int(month), 1)
        except ValueError:
            raise Http404

        my_reservations = Reservation.objects.filter(user=request.user.pk, date__gte=datetime.now().date())
        my_valid_reservations = Reservation.valid_reservations.filter(user=request.user.pk, date__gte=datetime.now().date())
        reservations = Reservation.valid_reservations.all()
        today = date.today()
        maximum_reservation_date = today + timedelta(days=90)
        terms_of_use = TermsOfUse.objects.last()

        context = {
            'my_reservations': my_reservations,
            'my_valid_reservations': my_valid_reservations,
            'reservations': reservations,
            'selected_date': selected_date,
            'calendar': tuple(_calendar(selected_date)),
            'next': selected_date + timedelta(days=31),
            'previous': selected_date - timedelta(days=1),
            'today': today,
            'minimum_reservation_date': today + timedelta(days=1),
            'maximum_reservation_date': maximum_reservation_date,
            'terms_of_use': terms_of_use
        }

        return render(request, 'reservations/reservations.html', context)


def _calendar(selected_date):
    year, month = selected_date.year, selected_date.month

    # Tapiri valid reservations (not cancelled nor expired)
    tp_filters = {'spot': 'TP', 'date__year':  year, 'date__month': month}
    tp_reservations = {b.date: b for b in Reservation.valid_reservations.filter(**tp_filters)}

    # Salão de Festas valid reservations (not cancelled nor expired)
    sf_reservations = Reservation.objects.filter(
        spot='SF', date__year=year, date__month=month,
    )

    sf_filters = {'spot': 'SF', 'date__year':  year, 'date__month': month}
    sf_reservations = {b.date: b for b in Reservation.valid_reservations.filter(**sf_filters)}

    # Tapiri das Arvores valid reservations (not cancelled nor expired)
    ta_reservations = Reservation.objects.filter(
        spot='TA', date__year=year, date__month=month,
    )
    ta_filters = {'spot': 'TA', 'date__year': year, 'date__month': month}
    ta_reservations = {b.date: b for b in Reservation.valid_reservations.filter(**ta_filters)}

    calendar = Calendar(firstweekday=6)
    today = date.today()
    for week in calendar.monthdatescalendar(year, month):
        yield [(day, tp_reservations.get(day), sf_reservations.get(day), ta_reservations.get(day)) for day in week]

apvma/reservations/templates/reservations/reservations.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/reservations.css' %}">
    <link rel="stylesheet" href="{% static 'css/reservations-mobile.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{% endblock stylesheet %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="container" align="center">
                <p class="calendar-message-{{ message.tags }}">{{ message }}</p>
            </div>
        {% endfor %}
    {% endif %}

    <h3>Minhas reservas</h3>
    {% if my_reservations %}
        <table width="85%" border="1" align="center">
            <tr align="center" height="40" bgcolor="#E3E3E3">
                <td><b>DATA</b></td>
                <td><b>LOCAL</b></td>
                <td><b>SITUAÇÃO DA RESERVA</b></td>
            </tr>
            {% for reservation in my_reservations %}
                <tr align="center" height="30" id="reservation_{{ reservation.pk }}"
                    bgcolor="{{ reservation.get_color }}">
                    <td>{{ reservation.date }}, {{ reservation.date|date:"l" }}</td>
                    <td>{{ reservation.get_spot_display }}</td>
                    <td>{{ reservation.status }}</td>
                </tr>
            {% endfor %}
        </table>

         <form action="." method="post">
        {% csrf_token %}
        <div class="row">
        <div class="col-md-10 col-md-offset-1">

          <input type="hidden" name="user" id="user" value="{{ request.user.pk }}">

          <div class="form-group">
            <label for="spot" style="padding-top: 5px">Cancelar reserva</label> <br/>
            <select class="form-control" style="width: 43%; display: inline-block" id="cancel_reservation" name="cancel_reservation">
                <option disabled selected value>-----</option>
                {% for reservation in my_valid_reservations %}
                    <option value="{{ reservation.pk }}">{{ reservation.date }} - {{ reservation.get_spot_display }}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary" name="cancel_reservation_button" id="cancel_reservation_button"
                  onclick="setRequiredTrue(cancel_reservation); removeRequired(spot); removeRequired(date); removeRequired(terms_of_use)">Cancelar reserva</button>
          </div>
        </div>
        </div>
         </form>

    {% else %}
        <p>Você não possui reservas agendadas.</p>
    {% endif %}


    <h3 id="disponibility">Disponibilidade</h3>
    <div align="center">
    <h5 class="calendar-tp-reservation-future" align="center" style="display: inline-block; width: 20%; padding: 5px">TP = Tapiri</h5>
    <h5 class="calendar-sf-reservation-future" align="center" style="display: inline-block; width: 20%; padding: 5px">SF = Salão de Festas</h5>
    <h5 class="calendar-ta-reservation-future" align="center" style="display: inline-block; width: 20%; padding: 5px">TA = Tapiri das Árvores</h5>
    <H5 class="calendar-tp-reservation-future" align="center" style="display: inline-block; width: 20%; padding: 5px; background-color: #D1E200">Aguardando pagamento</h5>
    </div>

    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <a href="{% url 'reservation_calendar' year=previous.year month=previous.month %}">« Mês anterior</a>
      </div>
      <div class="col-md-5 text-right">
        <a href="{% url 'reservation_calendar' year=next.year month=next.month %}">Próximo mês »</a>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">

        <table class="table table-bordered" style="border: 1px solid black" >

          <thead>
            <tr>
              <th colspan="7" style="border: 1px solid black" bgcolor="#C4C4C4">{{ selected_date|date:"F" }} {{ selected_date.year }}</th>
            </tr>
            <tr bgcolor="#E3E3E3">
              <th style="border: 1px solid black">Domingo</th>
              <th style="border: 1px solid black">Segunda</th>
              <th style="border: 1px solid black">Terça</th>
              <th style="border: 1px solid black">Quarta</th>
              <th style="border: 1px solid black">Quinta</th>
              <th style="border: 1px solid black">Sexta</th>
              <th style="border: 1px solid black">Sábado</th>
            </tr>
          </thead>

          <tbody>
            {% for week in calendar %}
            <tr style="height: 100px">
              {% for day, tp_reservation, sf_reservation, ta_reservation in week %}
              <td style="border: 1px solid black"
                {% if selected_date.month != day.month or day > maximum_reservation_date or day <= minimum_reservation_date %}
                class ="other"
                {% else %}
                id="day_{{ day.day }}"
                {% endif %}
              >
                <strong>{{ day.day }}</strong>
                <br>
                {% if tp_reservation and day >= today and day <= maximum_reservation_date %}
                    {% if tp_reservation.status == 'aguardando pagamento' %}
                        <p align="center" class="calendar-tp-reservation-future" style="background-color: #D1E200">
                            {{ tp_reservation.spot }} - {{ tp_reservation.user.username }}
                        </p>
                    {% else %}
                        <p align="center" class="calendar-tp-reservation-future">
                            {{ tp_reservation.spot }} - {{ tp_reservation.user.username }}
                        </p>
                    {% endif %}
                {% elif tp_reservation %}
                    <p align="center" class="calendar-tp-reservation-past">
                        {{ tp_reservation.spot }} - {{ tp_reservation.user.username }}
                    </p>
                {% endif %}
                {% if sf_reservation and day >= today and day <= maximum_reservation_date %}
                    {% if sf_reservation.status == 'aguardando pagamento' %}
                         <p align="center" class="calendar-sf-reservation-future" style="background-color: #D1E200">
                            {{ sf_reservation.spot }} - {{ sf_reservation.user.username }}
                        </p>
                    {% else %}
                        <p align="center" class="calendar-sf-reservation-future">
                            {{ sf_reservation.spot }} - {{ sf_reservation.user.username }}
                        </p>
                    {% endif %}
                {% elif sf_reservation %}
                    <p align="center" class="calendar-sf-reservation-past">
                        {{ sf_reservation.spot }} - {{ sf_reservation.user.username }}
                    </p>
                {% endif %}
                {% if ta_reservation and day >= today and day <= maximum_reservation_date %}
                    {% if ta_reservation.status == 'aguardando pagamento' %}
                        <p align="center" class="calendar-ta-reservation-future" style="background-color: #D1E200">
                            {{ ta_reservation.spot }} - {{ ta_reservation.user.username }}
                        </p>
                    {% else %}
                        <p align="center" class="calendar-ta-reservation-future">
                            {{ ta_reservation.spot }} - {{ ta_reservation.user.username }}
                        </p>
                    {% endif %}
                {% elif ta_reservation %}
                    <p align="center" class="calendar-ta-reservation-past">
                        {{ ta_reservation.spot }} - {{ ta_reservation.user.username }}
                    </p>
                {% else %}
                    <p>&nbsp;</p>
                {% endif %}
              </td>
              {% endfor %}
            </tr>
            {% endfor %}
          </tbody>

        </table>
      </div>
    </div>

        {% if request.user.is_authenticated %}
        <h3>Faça sua reserva</h3>

        <form action="." method="post" id="make_your_reservation">
        {% csrf_token %}

          <input type="hidden" name="user" id="user" value="{{ request.user.pk }}">

          <div class="form-group" align="left">
            <label for="spot" style="width: 25%; float: left; margin: 0 20px 0 0">
                <span style="display: block; margin: 0 0 3px">Local</span>
            <select class="form-control" id="spot" name="spot" style="width: 100%; display: inline-block">
                <option disabled selected value>-----</option>
                <option value="TP">Tapiri</option>
                <option value="SF">Salão de Festas</option>
                <option value="TA">Tapiri das Árvores</option>
            </select>
            </label>

            <label for="date" style="width: 25%; float: left; margin: 0 20px 0 0" id="reservation_date">
                <span style="display: block; margin: 0 0 3px">Data</span>
            <select class="form-control" name="date" id="date" style="width: 100%; display: inline-block">
              <option disabled selected value>-----</option>
              {% for week in calendar %}
              {% for day, tp_reservation, sf_reservation, ta_reservation in week %}
              {% if selected_date.month == day.month and day <= maximum_reservation_date and day > minimum_reservation_date %}
              {% if not tp_reservation or not sf_reservation or not ta_reservation %}
              <option value="{{ day.year }}-{{ day.month }}-{{ day.day}}">{{ day }}</option>
              {% endif %}
              {% endif %}
              {% endfor %}
              {% endfor %}
            </select>
            </label>


          <button type="submit" class="btn btn-primary" name="request_reservation_button" id="request_reservation_button"
                  onclick="setRequiredTrue(spot); setRequiredTrue(date); setRequiredTrue(terms_of_use); removeRequired(cancel_reservation)">Reservar</button>

          <br/>
          <div style="padding-top: 3px">
          <input type="checkbox" name="terms_of_use" id="terms_of_use">
              <label for="terms_of_use">Estou de acordo com os <a data-toggle="modal" href="#termsofuse">termos de uso</a>.</label>
          </div>
          <br/>
          <br/>
          </div>
        </form>

            <div class="container">
              <div id="termsofuse" class="modal fade" role="dialog" style="padding-top: 220px">
                  <div class="modal-dialog" style="max-width: 100%; width: 95%">

                      <div class="modal-content">
                          <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                          </div>
                          <div class="modal-body" style="height: 900px">
                              <embed src="{{ terms_of_use.file.url }}" frameborder="0" height="100%" width="100%"></embed>
                          </div>
                      </div>
                  </div>
              </div>
              </div>

        {% endif %}


    <script src="{% static 'js/django_csrf.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script language="JavaScript" type="text/javascript">
        function setRequiredTrue(field)
        {
            field.setAttribute('required', 'true');
        }
        function removeRequired(field)
        {
            field.removeAttribute('required');
        }
    </script>

{% endblock content %}